import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { en, zh } from '../src/client/locales.ts'

const css = readFileSync(
  new URL('../src/client/workbench/tender-workbench.module.css', import.meta.url),
  'utf8',
)
const queryView = readFileSync(new URL('../src/client/workbench/TenderQueryWorkspace.tsx', import.meta.url), 'utf8')
const screeningView = readFileSync(new URL('../src/client/workbench/TenderScreeningViews.tsx', import.meta.url), 'utf8')
const analysisView = readFileSync(new URL('../src/client/workbench/TenderAnalysisReviewViews.tsx', import.meta.url), 'utf8')
const reportView = readFileSync(new URL('../src/client/workbench/TenderReportView.tsx', import.meta.url), 'utf8')

describe('workbench visual contracts', () => {
  it('keeps typography readable and scoped without scaling the host', () => {
    expect(css).toContain('--tw-font-body: 14px')
    expect(css).toContain('--tw-font-table: 13px')
    expect(css).toContain('--tw-font-caption: 12px')
    expect(css).toContain('--tw-font-title: 20px')
    expect(css).toContain('container-name: tender-workbench')
    expect(css).not.toMatch(/\bzoom\s*:/u)
    expect(css).not.toMatch(/transform:\s*scale\(/u)
    expect(css).not.toMatch(/letter-spacing:\s*-/u)
    expect(css).toContain('.shell :where(button, input, select, textarea)')
    expect(css).toContain('.shell td')
  })

  it('folds by workbench container width and keeps the narrow primary action reachable', () => {
    expect(css).toContain('@container tender-workbench (max-width: 760px)')
    expect(css).toContain('@container tender-workbench (max-width: 600px)')
    expect(css).toContain('@container tender-workbench (max-width: 390px)')
    expect(css).toMatch(/@container tender-workbench \(max-width: 600px\)[\s\S]*?\.footer\s*\{[\s\S]*?flex-direction:\s*column/u)
    expect(css).toMatch(/@container tender-workbench \(max-width: 600px\)[\s\S]*?\.primary\s*\{[\s\S]*?width:\s*100%/u)
    expect(css).toMatch(/@container tender-workbench \(max-width: 390px\)[\s\S]*?\.footerHint\s*\{[\s\S]*?display:\s*none/u)
    expect(css).toMatch(/\.rulesLayout\s*\{[\s\S]*?grid-template-columns:\s*330px minmax\(480px, 1fr\)/u)
    expect(css).toMatch(/@container tender-workbench \(max-width: 760px\)[\s\S]*?\.rulesLayout,[\s\S]*?grid-template-columns:\s*1fr/u)
    expect(css).not.toContain('.suggestionDiff')
    expect(css).not.toContain('.agentSuggestion')
    expect(css).toMatch(/\.queryLayout\s*\{[\s\S]*?grid-template-columns:\s*minmax\(540px, 1fr\) 320px/u)
    expect(css).toMatch(/@container tender-workbench \(max-width: 1000px\)[\s\S]*?\.queryLayout,[\s\S]*?\.analysisWorkspace,[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\)/u)
    expect(css).toMatch(/@container tender-workbench \(max-width: 760px\)[\s\S]*?\.queryLayout,[\s\S]*?grid-template-columns:\s*1fr/u)
    expect(css).toMatch(/@container tender-workbench \(max-width: 760px\)[\s\S]*?\.queryPlan\s*\{\s*position:\s*static/u)
    expect(css).not.toMatch(/\.recordDetail\s*\{[^}]*order:\s*-1/u)
  })

  it('keeps one complete query surface and omits the closed S5.2 control list', () => {
    expect(queryView).toContain('TenderQueryWorkspace')
    expect(queryView).toContain('<details')
    expect(queryView).toContain('<summary><strong')
    expect(queryView).toContain('data-query-disclosure')
    expect(queryView).toContain('data-publish-extra="year"')
    expect(queryView).toContain('data-publish-extra="custom"')
    expect(queryView).toContain('data-region-token')
    expect(queryView).toContain('data-branch-count="7"')
    expect(queryView).toContain('data-branch-count="3"')
    expect(queryView).not.toContain("from '../fields/AdvancedFields.tsx'")
    expect(queryView).not.toContain("from '../fields/PublishTimeField.tsx'")
    expect(queryView).not.toContain("from '../fields/RegionField.tsx'")
    expect(queryView).not.toContain("from '../fields/StageField.tsx'")
    expect(queryView).toContain('data-plan-source')
    expect(queryView).not.toContain('smartSort')
    expect(screeningView).toContain('data-rule-workspace')
    expect(screeningView).toContain('data-rule-card')
    expect(screeningView).toContain('data-rule-editor')
    expect(screeningView).toContain('data-selected-rule-impact')
    expect(screeningView).toContain('data-rule-preview-grid')
    expect(screeningView).toContain('data-classification-overview')
    expect(screeningView).toContain('data-classification-details')
    expect(analysisView).toContain('data-analysis-layout')
    expect(analysisView).toContain('data-analysis-risk')
    expect(analysisView).toContain('data-analysis-verification')
    expect(css).toMatch(/\.analysisWorkspace\s*\{[\s\S]*?grid-template-columns:\s*350px minmax\(520px, 1fr\)/u)
    expect(css).toMatch(/\.reviewTable \[data-agent-recommendation\][^{]*\{[^}]*white-space:\s*nowrap/u)
    expect(css).toMatch(/\.reviewTiming\s*\{[^}]*white-space:\s*nowrap/u)
    expect(css).toMatch(/\.decisionSaveRow\s*\{[^}]*scroll-margin-block-end:/u)
    expect(css).toMatch(/\.reviewDetail\s*\{[\s\S]*?max-height:\s*calc\(100dvh - 220px\)[\s\S]*?overflow-y:\s*auto/u)
    expect(css).toMatch(/@container tender-workbench \(max-width: 1000px\)[\s\S]*?\.reviewDetail\s*\{[^}]*max-height:\s*none;[^}]*overflow-y:\s*visible/u)
    expect(screeningView).not.toContain('createAdjustRulesIntent')
    expect(screeningView).not.toContain('adjustPlaceholder')
    expect(screeningView).not.toMatch(/导入规则|复制规则|添加条件组|继续询问/u)
  })

  it('keeps Chinese and English locale keys complete', () => {
    expect(Object.keys(en).sort()).toEqual(Object.keys(zh).sort())
  })

  it('keeps the S5.4 prototype hierarchy, responsive geometry, and closed omission list', () => {
    expect(reportView).toContain("const REPORT_TABS = ['summary', 'charts', 'opportunities', 'files', 'provenance']")
    expect(reportView).toContain('role="tablist"')
    expect(reportView).toContain('role="tabpanel"')
    expect(reportView).toContain('hidden={selectedTab !== tab}')
    expect(reportView.indexOf('<ReportHero')).toBeLessThan(reportView.indexOf('className={css.reportTabs}'))
    expect(reportView).not.toMatch(/在线预览|版本对比|用户排除原因 Top 5/u)
    expect(css).toMatch(/\.deliveryHeroGrid\s*\{[^}]*grid-template-columns:\s*minmax\(0, 1\.35fr\) minmax\(280px, \.65fr\)/u)
    expect(css).toMatch(/\.reportKpis\s*\{[^}]*grid-template-columns:\s*repeat\(6,/u)
    expect(css).toMatch(/@container tender-workbench \(max-width: 1000px\)[\s\S]*?\.deliveryHeroGrid,[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\)/u)
    expect(css).toMatch(/@container tender-workbench \(max-width: 760px\)[\s\S]*?\.reportKpis,[\s\S]*?grid-template-columns:\s*repeat\(2,/u)
    expect(css).toMatch(/@container tender-workbench \(max-width: 600px\)[\s\S]*?\.footer\[data-workbench-phase="delivery"\][\s\S]*?flex-direction:\s*row/u)
    expect(css).toContain('--tw-surface: var(--qcc-surface)')
    expect(css).toContain('--tw-ink: var(--qcc-text)')
  })
})
